"""The first migration for this app's three tables.

Generated by `makemigrations` and then reflowed by hand so that it passes
the same linter as the rest of the repository - the columns and the
constraint are exactly what `makemigrations --check` expects.

**socialchimp did not write this, and it has none of its own.** The library
creates no tables and runs no migrations on any framework, which is why the
same library serves Django, FastAPI and Flask. These are this project's
tables and this project's migration.
"""

from __future__ import annotations

from typing import Any, ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create SocialConnection, SocialApp and PostAttempt."""

    initial = True

    dependencies: ClassVar[list[Any]] = []

    operations: ClassVar[list[Any]] = [
        migrations.CreateModel(
            name="SocialConnection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=32)),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("account_id", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refresh_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("scopes", models.JSONField(default=list)),
                ("extra", models.JSONField(default=dict)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("platform", "account_name")},
        ),
        migrations.CreateModel(
            name="SocialApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=32)),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "host"),
                        name="one_app_per_platform_and_host",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="PostAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_id", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=32)),
                ("account_name", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("state", models.CharField(blank=True, default="", max_length=32)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={"ordering": ("-attempted_at",)},
        ),
    ]
